

signin_loc="//div[@class='signin_head']//span[@id='headtitle' and text()='Sign in']"
googlesign_loc="//span[@aria-label='Sign in with Google']"
companyname_loc="//crm-create-fields[@id='Leads_fldRow_COMPANY']//input"
lastname_loc="//input[@id='Crm_Leads_LASTNAME_LInput']"
saveleadbtn_loc="//button[@id='crm_create_savebutn']"
title_loc="//input[@id='Crm_Leads_DESIGNATION_LInput']"
leaderrmsg_loc="//span[@id='errorMsg_Crm_Leads_COMPANY']"
leadtable_loc="//lyte-yield[@yield-name='body-lookup']//a"
leadedit_loc="//button[@aria-label='Edit']"
companynameedit_loc="//input[@id='inputId']"
cancelbtn_loc="//button[@id='crm_create_cancelbutn']"
existingleadnm_loc="//span[@class='cxElemCompViewWrap']"
moreoptions_loc="//button[@aria-label='More Options']"
delete_loc="//lyte-menu-item[text()='Delete']"
accept_loc="//button[@type='accept']"
reject_loc="//button[@type='reject']"
login_loc="//input[@id='login_id']"
nextbtn_loc="//button[@id='nextbtn']"
password_loc="//input[@id='password']"
totalrecrds_loc="//span[text()='Total Records']"
createleadsec_loc="//button[text()='Create Lead']"
leadflow_loc="//crm-create-fields[@id='Leads_fldRow_COMPANY']//input"
crmsec_loc="//div[text()='CRM']"
leads_loc="//a//span[text()='Leads']"
leadbody_loc="//lyte-yield[@yield-name='body-lookup']"
search_loc="//span[@id='alphaSearch']"
searchc_loc="//lyte-menu-item[@id='C']"
